app_users_index:
    path: /users
    controller: 'App\Controller\Web\UsersController::index'
    methods: GET

app_users_create:
    path: /users/create
    controller: 'App\Controller\Web\UsersController::create'
    methods: [GET, POST]

app_users_edit:
    path: /users/edit/{id}
    controller: 'App\Controller\Web\UsersController::edit'
    methods: [GET, POST]

app_users_delete:
    path: /users/delete/{id}
    controller: 'App\Controller\Web\UsersController::delete'
    methods: GET

app_users_show:
    path: /users/{id}
    controller: 'App\Controller\Web\UsersController::show'
    methods: GET

app_user_add_to_group:
    path: /users/add-to-group/{userId}/{groupId}
    controller: 'App\Controller\Web\UsersController::addToGroup'
    methods: POST

app_user_remove_from_group:
    path: /users/remove-from-group/{userId}/{groupId}
    controller: 'App\Controller\Web\UsersController::removeFromGroup'
    methods: POST
